---
- name: Read-only tests on variable hosts to get information
  hosts: "{{ var_hosts }}"
  gather_facts: yes

  tasks:
    - name: Get details about host (Ansible facts, hostvar expressions, undefined variables, ...)
      ansible.builtin.debug:
        msg:
          - "ansible_facts.os_family      : {{ ansible_facts.os_family }}"
          - "ansible_facts.distribution   : {{ ansible_facts.distribution }}"
          - "var_does_not_exist           : {{ var_does_not_exist | default ('Defaulted to this value') }}"
