---
- name: Get Azure data
  hosts: localhost
  connection: local

  tasks:
    - name: Block
      block:
        - name: General tasks
          ansible.builtin.include_tasks: includes/general.yaml
        - name: Azure tasks
          ansible.builtin.include_tasks: includes/azure.yaml
      rescue:
        - name: Rescued, will continue with next Play
          ansible.builtin.debug:
            msg: "Rescued, will continue with next Play"

- name: Get local data from Mac
  hosts: localhost
  connection: local

  tasks:
    - name: General tasks
      ansible.builtin.include_tasks: includes/general.yaml

- name: Update raspberry
  hosts: raspberry
  gather_facts: true

  tasks:
    - name: Block
      block:
        - name: General tasks
          ansible.builtin.include_tasks: includes/general.yaml
        - name: Raspberry tasks
          ansible.builtin.include_tasks: includes/raspberry.yaml
