---
- name: Test roles
  vars:
    var_hosts: "localhost"
  hosts: "{{ var_hosts }}"

  roles:
    - role: common
    - role: raspberry
      when: ansible_facts['os_family'] == 'Debian'
    - role: mac
      when: ansible_facts['os_family'] == 'Darwin'
