---
- name: Read-only tests on variable hosts to get information
  hosts: "{{ var_hosts }}"
  gather_facts: yes

  tasks:
    - name: Get details about host (Ansible facts, undefined variables, ...)
      ansible.builtin.debug:
        msg:
          - "ansible_facts.os_family      : {{ ansible_facts.os_family }}"
          - "ansible_facts.distribution   : {{ ansible_facts.distribution }}"
          - "var_does_not_exist           : {{ var_does_not_exist | default ('Defaulted to this value') }}"

    - name: Get OS uptime
      ansible.builtin.command: uptime
      changed_when: false
      register: result

    - name: Display results for OS uptime command
      ansible.builtin.debug:
        msg:
          - "Start command: {{ result.start }}"
          - "End command  : {{ result.end }}"
          - "{{ result.cmd }}"
          - "{{ result.stdout }}"
