- name: Ping
  ansible.builtin.ping:

- name: Get system info
  ansible.builtin.command: uname -a
  register: output
  changed_when: false

- name: Display system info
  ansible.builtin.debug:
    var: output.stdout

- name: Display inventory variable 'env'
  ansible.builtin.debug:
    var: env

- name: Download file
  ansible.builtin.get_url:
    url: https://filesamples.com/samples/document/txt/sample2.txt
    dest: ./download.txt
    mode: '0600'
    checksum: md5:ba0f0dfefe865df90fe4e80a94acc275

- name: Delete downloaded file
  ansible.builtin.file:
    path: ./download.txt
    state: absent
