- name: Remove useless packages from the cache
  become: true
  ansible.builtin.apt:
    autoclean: true

- name: Remove dependencies that are no longer required
  become: true
  ansible.builtin.apt:
    autoremove: true

- name: Run the equivalent of "apt-get clean" as a separate step
  become: true
  ansible.builtin.apt:
    clean: true

- name: Pi-hole tasks
  ansible.builtin.import_tasks: pihole.yaml

- name: NordVPN tasks
  ansible.builtin.import_tasks: nordvpn.yaml
