- name: Update cache if the last one is more than 3600 seconds ago
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Remove useless packages from the cache
  become: true
  ansible.builtin.apt:
    autoclean: true

- name: Remove dependencies that are no longer required
  become: true
  ansible.builtin.apt:
    autoremove: true

- name: Run the equivalent of "apt-get clean" as a separate step
  become: true
  ansible.builtin.apt:
    clean: true

- name: Pi-hole tasks
  ansible.builtin.import_tasks: pihole.yaml

- name: NordVPN tasks
  ansible.builtin.import_tasks: nordvpn.yaml
