- name: Update all packages to their latest version
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Remove useless packages from the cache
  become: true
  ansible.builtin.apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  become: true
  ansible.builtin.apt:
    autoremove: yes

- name: Run the equivalent of "apt-get clean" as a separate step
  become: true
  apt:
    clean: yes

- name: Pi-hole tasks
  import_tasks: pihole.yaml

- name: NordVPN tasks
  import_tasks: nordvpn.yaml
