- name: NordVPN - Install GPG key and APT repo
  become: true
  ansible.builtin.apt:
    deb: "{{ nordvpn_deb_package }}"
    state: present

- name: NordVPN - Install
  become: true
  ansible.builtin.apt:
    name: nordvpn
    state: present

- name: NordVPN - Add user wim to group nordvpn
  become: true
  ansible.builtin.user:
    name: wim
    groups: nordvpn
    append: yes

- name: NordVPN - Get current settings
  ansible.builtin.command: nordvpn settings
  register: nordvpn_settings
  changed_when: false

- name: NordVPN - Add rules to allow ports
  ansible.builtin.command: nordvpn whitelist add port {{ item }}
  loop: "{{ allowed_ports }}"
  when: "'{{ item }} (UDP|TCP)' not in nordvpn_settings.stdout"

- name: NordVPN - Add a rule to allow subnet {{ home_subnet }}
  ansible.builtin.command: nordvpn whitelist add subnet {{ home_subnet }}
  when: "'{{ home_subnet }}' not in nordvpn_settings.stdout"
