- name: Ping test
  ansible.builtin.ping:

- name: Get OS uptime
  ansible.builtin.command: uptime
  changed_when: false
  register: result

- name: Display OS data
  ansible.builtin.debug:
    msg:
      - "Start: {{ result.start }}"
      - "End: {{ result.end }}"
      - "{{ result.cmd }}"
      - "{{ result.stdout }}"
