- name: Copy playbook file
  ansible.builtin.copy:
    src: ./playbook-test-blocks-and-includes.yaml
    dest: /home/wim/inventory.yaml
    mode: '0600'

- name: Display Python version
  ansible.builtin.debug:
    var: ansible_facts['python_version']

- name: Get system information
  ansible.builtin.command: uname -a
  changed_when: false
  register: system_info

- name: Save result to a file
  ansible.builtin.copy:
    content: |
      System information: {{ system_info.stdout }}
      Python version: {{ ansible_facts['python_version'] }}
    dest: "/home/wim/system_info.txt"
    mode: '0600'
  register: result

- name: Debug file
  ansible.builtin.debug:
    var: result

- name: Add specific block to a file
  ansible.builtin.blockinfile:
    path: /home/wim/system_info2.txt
    marker: "### {mark} ANSIBLE MANAGED BLOCK ###"
    block: |
      This block of lines will always be present in the (existing) target file.
      Block will be surrounded by markers.
      Rest of the file can be maintained without triggering a change for this task.
