name: Ansible linting validations

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: ls ${{ github.workspace }}
