name: Ansible linting validations

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      playbook:
        description: 'Playbook name'
        required: true
        type: string

jobs:
  Ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
    
      - name: Playbook name
        run: echo ${{ inputs.playbook }
