name: Ansible linting validations

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      playbook:
        description: 'Playbook name'
        required: true
        type: string
        default: 'playbook-test-roles.yaml'

jobs:
  Ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.11

      - name: Install Ansible Lint
        run: pip install ansible-lint

      - name: Ansible Lint version
        run: ansible-lint --version
    
      - name: Playbook name
        run: echo ${{ inputs.playbook }}
