name: Ansible linting validations

on:
  pull_request:
    branches:
      - main

jobs:
  Ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
    
      - name: List files in the repository
        run: ls ${{ github.workspace }}
